### ISSUE TITLE
Folder title organization + Folders in folders crash the app/load a blank page.

### ISSUE THREAD

**Issue by AsiagoPizza** [darkxex/CuteManga#9]
The folder titles aren't properly organized. Please fix this issue.

![2021123012164900-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/96790320/147774421-cdfaf7b7-9a2f-4e50-8058-88ae68a6a234.jpg)

Also, whenever I access a folder in a folder, either it crashes the app or loads a blank page. There should be an update where you can access folders in folders without any issues for better organization.

NOTE: I do not know how to make this as a pull request as this was so complex to me.

**Comment by darkxex** [comment]
My friend I don't have plans for more updates incoming.

**Comment by AsiagoPizza** [comment]
> My friend I don't have plans for more updates incoming.

So this will be the final version of the app? Even without organization and convenience? 

If so, that's rather disappointing, though I do not hate the app by itself.

**Comment by darkxex** [comment]
hi friend, i updated to 1.0.4, the only change was that it should already show you the folders in alphabetical order, but it still doesn't support and I doubt it supports folders within folders. Greetings.

**Comment by NostalgicMysticalCat** [comment]
Hello, I tested the update for myself and it certainly appears the folder titles are now organized by name. Thank you!

![2021123021484700-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/96790320/147800186-1f596ed5-7d5c-452a-8260-e83218d0a6cc.jpg)

Also, will you still eventually add sub directory support? I still encourage you should since it would add more convenience to the app use in case you have more mangas, you don't have to keep scrolling all the way down.

Would look something like this:

/CuteManga/Naruto/Chapter1/

**Another issue I noticed for myself:** Folder titles with apostrophes/punctuations do not show up in the list at all. Can that be fixed too? This is why Chapter 10 of Edens Zero is not showing up on the list.

**Comment by darkxex** [comment]
not for now.
